/*
Package ygotnddptarget is a generated package which contains definitions
of structs which represent a YANG schema. The generated schema can be
compressed by a series of transformations (compression was false
in this case).

This package was generated by /Users/henderiw/CodeProjects/tmp/ygot/genutil/names.go
using the following YANG input files:
	- /Users/henderiw/CodeProjects/yang/ndd/0_1_0/combined/ndd-target.yang
Imported modules were sourced from:
	- /Users/henderiw/CodeProjects/yang/ndd/0_1_0/combined/...
*/
package ygotnddtarget

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/openconfig/goyang/pkg/yang"
	"github.com/openconfig/ygot/ygot"
	"github.com/openconfig/ygot/ytypes"
)

// Binary is a type that is used for fields that have a YANG type of
// binary. It is used such that binary fields can be distinguished from
// leaf-lists of uint8s (which are mapped to []uint8, equivalent to
// []byte in reflection).
type Binary []byte

// YANGEmpty is a type that is used for fields that have a YANG type of
// empty. It is used such that empty fields can be distinguished from boolean fields
// in the generated code.
type YANGEmpty bool

// UnionInt8 is an int8 type assignable to unions of which it is a subtype.
type UnionInt8 int8

// UnionInt16 is an int16 type assignable to unions of which it is a subtype.
type UnionInt16 int16

// UnionInt32 is an int32 type assignable to unions of which it is a subtype.
type UnionInt32 int32

// UnionInt64 is an int64 type assignable to unions of which it is a subtype.
type UnionInt64 int64

// UnionUint8 is a uint8 type assignable to unions of which it is a subtype.
type UnionUint8 uint8

// UnionUint16 is a uint16 type assignable to unions of which it is a subtype.
type UnionUint16 uint16

// UnionUint32 is a uint32 type assignable to unions of which it is a subtype.
type UnionUint32 uint32

// UnionUint64 is a uint64 type assignable to unions of which it is a subtype.
type UnionUint64 uint64

// UnionFloat64 is a float64 type assignable to unions of which it is a subtype.
type UnionFloat64 float64

// UnionString is a string type assignable to unions of which it is a subtype.
type UnionString string

// UnionBool is a bool type assignable to unions of which it is a subtype.
type UnionBool bool

// UnionUnsupported is an interface{} wrapper type for unsupported types. It is
// assignable to unions of which it is a subtype.
type UnionUnsupported struct {
	Value interface{}
}

var (
	SchemaTree map[string]*yang.Entry
)

func init() {
	var err error
	if SchemaTree, err = UnzipSchema(); err != nil {
		panic("schema error: " + err.Error())
	}
}

// Schema returns the details of the generated schema.
func Schema() (*ytypes.Schema, error) {
	uzp, err := UnzipSchema()
	if err != nil {
		return nil, fmt.Errorf("cannot unzip schema, %v", err)
	}

	return &ytypes.Schema{
		Root:       &Device{},
		SchemaTree: uzp,
		Unmarshal:  Unmarshal,
	}, nil
}

// UnzipSchema unzips the zipped schema and returns a map of yang.Entry nodes,
// keyed by the name of the struct that the yang.Entry describes the schema for.
func UnzipSchema() (map[string]*yang.Entry, error) {
	var schemaTree map[string]*yang.Entry
	var err error
	if schemaTree, err = ygot.GzipToSchema(ySchema); err != nil {
		return nil, fmt.Errorf("could not unzip the schema; %v", err)
	}
	return schemaTree, nil
}

// Unmarshal unmarshals data, which must be RFC7951 JSON format, into
// destStruct, which must be non-nil and the correct GoStruct type. It returns
// an error if the destStruct is not found in the schema or the data cannot be
// unmarshaled. The supplied options (opts) are used to control the behaviour
// of the unmarshal function - for example, determining whether errors are
// thrown for unknown fields in the input JSON.
func Unmarshal(data []byte, destStruct ygot.ValidatedGoStruct, opts ...ytypes.UnmarshalOpt) error {
	tn := reflect.TypeOf(destStruct).Elem().Name()
	schema, ok := SchemaTree[tn]
	if !ok {
		return fmt.Errorf("could not find schema for type %s", tn)
	}
	var jsonTree interface{}
	if err := json.Unmarshal([]byte(data), &jsonTree); err != nil {
		return err
	}
	return ytypes.Unmarshal(schema, destStruct, jsonTree, opts...)
}

// Device represents the /device YANG schema element.
type Device struct {
	TargetEntry map[string]*NddTarget_TargetEntry `path:"target-entry" module:"ndd-target"`
}

// IsYANGGoStruct ensures that Device implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*Device) IsYANGGoStruct() {}

// NewTargetEntry creates a new entry in the TargetEntry list of the
// Device struct. The keys of the list are populated from the input
// arguments.
func (t *Device) NewTargetEntry(Name string) (*NddTarget_TargetEntry, error) {

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.TargetEntry == nil {
		t.TargetEntry = make(map[string]*NddTarget_TargetEntry)
	}

	key := Name

	// Ensure that this key has not already been used in the
	// list. Keyed YANG lists do not allow duplicate keys to
	// be created.
	if _, ok := t.TargetEntry[key]; ok {
		return nil, fmt.Errorf("duplicate key %v for list TargetEntry", key)
	}

	t.TargetEntry[key] = &NddTarget_TargetEntry{
		Name: &Name,
	}

	return t.TargetEntry[key], nil
}

// GetOrCreateTargetEntry retrieves the value with the specified keys from
// the receiver Device. If the entry does not exist, then it is created.
// It returns the existing or new list member.
func (t *Device) GetOrCreateTargetEntry(Name string) *NddTarget_TargetEntry {

	key := Name

	if v, ok := t.TargetEntry[key]; ok {
		return v
	}
	// Panic if we receive an error, since we should have retrieved an existing
	// list member. This allows chaining of GetOrCreate methods.
	v, err := t.NewTargetEntry(Name)
	if err != nil {
		panic(fmt.Sprintf("GetOrCreateTargetEntry got unexpected error: %v", err))
	}
	return v
}

// GetTargetEntry retrieves the value with the specified key from
// the TargetEntry map field of Device. If the receiver is nil, or
// the specified key is not present in the list, nil is returned such that Get*
// methods may be safely chained.
func (t *Device) GetTargetEntry(Name string) *NddTarget_TargetEntry {

	if t == nil {
		return nil
	}

	key := Name

	if lm, ok := t.TargetEntry[key]; ok {
		return lm
	}
	return nil
}

// DeleteTargetEntry deletes the value with the specified keys from
// the receiver Device. If there is no such element, the function
// is a no-op.
func (t *Device) DeleteTargetEntry(Name string) {
	key := Name

	delete(t.TargetEntry, key)
}

// AppendTargetEntry appends the supplied NddTarget_TargetEntry struct to the
// list TargetEntry of Device. If the key value(s) specified in
// the supplied NddTarget_TargetEntry already exist in the list, an error is
// returned.
func (t *Device) AppendTargetEntry(v *NddTarget_TargetEntry) error {
	if v.Name == nil {
		return fmt.Errorf("invalid nil key received for Name")
	}

	key := *v.Name

	// Initialise the list within the receiver struct if it has not already been
	// created.
	if t.TargetEntry == nil {
		t.TargetEntry = make(map[string]*NddTarget_TargetEntry)
	}

	if _, ok := t.TargetEntry[key]; ok {
		return fmt.Errorf("duplicate key for list TargetEntry %v", key)
	}

	t.TargetEntry[key] = v
	return nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *Device) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["Device"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *Device) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// Device belongs.
func (*Device) ΛBelongingModule() string {
	return ""
}

// NddTarget_TargetEntry represents the /ndd-target/target-entry YANG schema element.
type NddTarget_TargetEntry struct {
	AdminState  E_NddCommon_AdminState        `path:"admin-state" module:"ndd-target"`
	Config      *NddTarget_TargetEntry_Config `path:"config" module:"ndd-target"`
	Description *string                       `path:"description" module:"ndd-target"`
	Name        *string                       `path:"name" module:"ndd-target"`
	State       *NddTarget_TargetEntry_State  `path:"state" module:"ndd-target"`
	VendorType  E_NddTarget_VendorType        `path:"vendor-type" module:"ndd-target"`
}

// IsYANGGoStruct ensures that NddTarget_TargetEntry implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*NddTarget_TargetEntry) IsYANGGoStruct() {}

// GetOrCreateConfig retrieves the value of the Config field
// or returns the existing field if it already exists.
func (t *NddTarget_TargetEntry) GetOrCreateConfig() *NddTarget_TargetEntry_Config {
	if t.Config != nil {
		return t.Config
	}
	t.Config = &NddTarget_TargetEntry_Config{}
	return t.Config
}

// GetOrCreateState retrieves the value of the State field
// or returns the existing field if it already exists.
func (t *NddTarget_TargetEntry) GetOrCreateState() *NddTarget_TargetEntry_State {
	if t.State != nil {
		return t.State
	}
	t.State = &NddTarget_TargetEntry_State{}
	return t.State
}

// GetConfig returns the value of the Config struct pointer
// from NddTarget_TargetEntry. If the receiver or the field Config is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *NddTarget_TargetEntry) GetConfig() *NddTarget_TargetEntry_Config {
	if t != nil && t.Config != nil {
		return t.Config
	}
	return nil
}

// GetState returns the value of the State struct pointer
// from NddTarget_TargetEntry. If the receiver or the field State is nil, nil
// is returned such that the Get* methods can be safely chained.
func (t *NddTarget_TargetEntry) GetState() *NddTarget_TargetEntry_State {
	if t != nil && t.State != nil {
		return t.State
	}
	return nil
}

// ΛListKeyMap returns the keys of the NddTarget_TargetEntry struct, which is a YANG list entry.
func (t *NddTarget_TargetEntry) ΛListKeyMap() (map[string]interface{}, error) {
	if t.Name == nil {
		return nil, fmt.Errorf("nil value for key Name")
	}

	return map[string]interface{}{
		"name": *t.Name,
	}, nil
}

// Validate validates s against the YANG schema corresponding to its type.
func (t *NddTarget_TargetEntry) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["NddTarget_TargetEntry"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *NddTarget_TargetEntry) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// NddTarget_TargetEntry belongs.
func (*NddTarget_TargetEntry) ΛBelongingModule() string {
	return "ndd-target"
}

// NddTarget_TargetEntry_Config represents the /ndd-target/target-entry/config YANG schema element.
type NddTarget_TargetEntry_Config struct {
	Address           *string              `path:"address" module:"ndd-target"`
	CredentialName    *string              `path:"credential-name" module:"ndd-target"`
	Encoding          E_NddTarget_Encoding `path:"encoding" module:"ndd-target"`
	Insecure          *bool                `path:"insecure" module:"ndd-target"`
	Protocol          E_NddTarget_Protocol `path:"protocol" module:"ndd-target"`
	Proxy             *string              `path:"proxy" module:"ndd-target"`
	SkipVerify        *bool                `path:"skip-verify" module:"ndd-target"`
	TlsCredentialName *string              `path:"tls-credential-name" module:"ndd-target"`
}

// IsYANGGoStruct ensures that NddTarget_TargetEntry_Config implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*NddTarget_TargetEntry_Config) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *NddTarget_TargetEntry_Config) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["NddTarget_TargetEntry_Config"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *NddTarget_TargetEntry_Config) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// NddTarget_TargetEntry_Config belongs.
func (*NddTarget_TargetEntry_Config) ΛBelongingModule() string {
	return "ndd-target"
}

// NddTarget_TargetEntry_State represents the /ndd-target/target-entry/state YANG schema element.
type NddTarget_TargetEntry_State struct {
	Hostname           *string                `path:"hostname" module:"ndd-target"`
	Kind               *string                `path:"kind" module:"ndd-target"`
	MacAddress         *string                `path:"mac-address" module:"ndd-target"`
	SerialNumber       *string                `path:"serial-number" module:"ndd-target"`
	SupportedEncodings []string               `path:"supported-encodings" module:"ndd-target"`
	SwVersion          *string                `path:"sw-version" module:"ndd-target"`
	VendorType         E_NddTarget_VendorType `path:"vendor-type" module:"ndd-target"`
}

// IsYANGGoStruct ensures that NddTarget_TargetEntry_State implements the yang.GoStruct
// interface. This allows functions that need to handle this struct to
// identify it as being generated by ygen.
func (*NddTarget_TargetEntry_State) IsYANGGoStruct() {}

// Validate validates s against the YANG schema corresponding to its type.
func (t *NddTarget_TargetEntry_State) Validate(opts ...ygot.ValidationOption) error {
	if err := ytypes.Validate(SchemaTree["NddTarget_TargetEntry_State"], t, opts...); err != nil {
		return err
	}
	return nil
}

// ΛEnumTypeMap returns a map, keyed by YANG schema path, of the enumerated types
// that are included in the generated code.
func (t *NddTarget_TargetEntry_State) ΛEnumTypeMap() map[string][]reflect.Type { return ΛEnumTypes }

// ΛBelongingModule returns the name of the module in whose namespace
// NddTarget_TargetEntry_State belongs.
func (*NddTarget_TargetEntry_State) ΛBelongingModule() string {
	return "ndd-target"
}

// E_NddCommon_AdminState is a derived int64 type which is used to represent
// the enumerated node NddCommon_AdminState. An additional value named
// NddCommon_AdminState_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_NddCommon_AdminState int64

// IsYANGGoEnum ensures that NddCommon_AdminState implements the yang.GoEnum
// interface. This ensures that NddCommon_AdminState can be identified as a
// mapped type for a YANG enumeration.
func (E_NddCommon_AdminState) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  NddCommon_AdminState.
func (E_NddCommon_AdminState) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum }

// String returns a logging-friendly string for E_NddCommon_AdminState.
func (e E_NddCommon_AdminState) String() string {
	return ygot.EnumLogString(e, int64(e), "E_NddCommon_AdminState")
}

const (
	// NddCommon_AdminState_UNSET corresponds to the value UNSET of NddCommon_AdminState
	NddCommon_AdminState_UNSET E_NddCommon_AdminState = 0
	// NddCommon_AdminState_enable corresponds to the value enable of NddCommon_AdminState
	NddCommon_AdminState_enable E_NddCommon_AdminState = 1
	// NddCommon_AdminState_disable corresponds to the value disable of NddCommon_AdminState
	NddCommon_AdminState_disable E_NddCommon_AdminState = 2
)

// E_NddTarget_Encoding is a derived int64 type which is used to represent
// the enumerated node NddTarget_Encoding. An additional value named
// NddTarget_Encoding_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_NddTarget_Encoding int64

// IsYANGGoEnum ensures that NddTarget_Encoding implements the yang.GoEnum
// interface. This ensures that NddTarget_Encoding can be identified as a
// mapped type for a YANG enumeration.
func (E_NddTarget_Encoding) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  NddTarget_Encoding.
func (E_NddTarget_Encoding) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum }

// String returns a logging-friendly string for E_NddTarget_Encoding.
func (e E_NddTarget_Encoding) String() string {
	return ygot.EnumLogString(e, int64(e), "E_NddTarget_Encoding")
}

const (
	// NddTarget_Encoding_UNSET corresponds to the value UNSET of NddTarget_Encoding
	NddTarget_Encoding_UNSET E_NddTarget_Encoding = 0
	// NddTarget_Encoding_JSON corresponds to the value JSON of NddTarget_Encoding
	NddTarget_Encoding_JSON E_NddTarget_Encoding = 1
	// NddTarget_Encoding_JSON_IETF corresponds to the value JSON_IETF of NddTarget_Encoding
	NddTarget_Encoding_JSON_IETF E_NddTarget_Encoding = 2
	// NddTarget_Encoding_BYTES corresponds to the value BYTES of NddTarget_Encoding
	NddTarget_Encoding_BYTES E_NddTarget_Encoding = 3
	// NddTarget_Encoding_PROTOBUF corresponds to the value PROTOBUF of NddTarget_Encoding
	NddTarget_Encoding_PROTOBUF E_NddTarget_Encoding = 4
	// NddTarget_Encoding_ASCII corresponds to the value ASCII of NddTarget_Encoding
	NddTarget_Encoding_ASCII E_NddTarget_Encoding = 5
)

// E_NddTarget_Protocol is a derived int64 type which is used to represent
// the enumerated node NddTarget_Protocol. An additional value named
// NddTarget_Protocol_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_NddTarget_Protocol int64

// IsYANGGoEnum ensures that NddTarget_Protocol implements the yang.GoEnum
// interface. This ensures that NddTarget_Protocol can be identified as a
// mapped type for a YANG enumeration.
func (E_NddTarget_Protocol) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  NddTarget_Protocol.
func (E_NddTarget_Protocol) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum }

// String returns a logging-friendly string for E_NddTarget_Protocol.
func (e E_NddTarget_Protocol) String() string {
	return ygot.EnumLogString(e, int64(e), "E_NddTarget_Protocol")
}

const (
	// NddTarget_Protocol_UNSET corresponds to the value UNSET of NddTarget_Protocol
	NddTarget_Protocol_UNSET E_NddTarget_Protocol = 0
	// NddTarget_Protocol_gnmi corresponds to the value gnmi of NddTarget_Protocol
	NddTarget_Protocol_gnmi E_NddTarget_Protocol = 1
	// NddTarget_Protocol_netconf corresponds to the value netconf of NddTarget_Protocol
	NddTarget_Protocol_netconf E_NddTarget_Protocol = 2
)

// E_NddTarget_VendorType is a derived int64 type which is used to represent
// the enumerated node NddTarget_VendorType. An additional value named
// NddTarget_VendorType_UNSET is added to the enumeration which is used as
// the nil value, indicating that the enumeration was not explicitly set by
// the program importing the generated structures.
type E_NddTarget_VendorType int64

// IsYANGGoEnum ensures that NddTarget_VendorType implements the yang.GoEnum
// interface. This ensures that NddTarget_VendorType can be identified as a
// mapped type for a YANG enumeration.
func (E_NddTarget_VendorType) IsYANGGoEnum() {}

// ΛMap returns the value lookup map associated with  NddTarget_VendorType.
func (E_NddTarget_VendorType) ΛMap() map[string]map[int64]ygot.EnumDefinition { return ΛEnum }

// String returns a logging-friendly string for E_NddTarget_VendorType.
func (e E_NddTarget_VendorType) String() string {
	return ygot.EnumLogString(e, int64(e), "E_NddTarget_VendorType")
}

const (
	// NddTarget_VendorType_UNSET corresponds to the value UNSET of NddTarget_VendorType
	NddTarget_VendorType_UNSET E_NddTarget_VendorType = 0
	// NddTarget_VendorType_undefined corresponds to the value undefined of NddTarget_VendorType
	NddTarget_VendorType_undefined E_NddTarget_VendorType = 1
	// NddTarget_VendorType_nokia_srl corresponds to the value nokia_srl of NddTarget_VendorType
	NddTarget_VendorType_nokia_srl E_NddTarget_VendorType = 2
	// NddTarget_VendorType_nokia_sros corresponds to the value nokia_sros of NddTarget_VendorType
	NddTarget_VendorType_nokia_sros E_NddTarget_VendorType = 3
)

// ΛEnum is a map, keyed by the name of the type defined for each enum in the
// generated Go code, which provides a mapping between the constant int64 value
// of each value of the enumeration, and the string that is used to represent it
// in the YANG schema. The map is named ΛEnum in order to avoid clash with any
// valid YANG identifier.
var ΛEnum = map[string]map[int64]ygot.EnumDefinition{
	"E_NddCommon_AdminState": {
		1: {Name: "enable"},
		2: {Name: "disable"},
	},
	"E_NddTarget_Encoding": {
		1: {Name: "JSON"},
		2: {Name: "JSON_IETF"},
		3: {Name: "BYTES"},
		4: {Name: "PROTOBUF"},
		5: {Name: "ASCII"},
	},
	"E_NddTarget_Protocol": {
		1: {Name: "gnmi"},
		2: {Name: "netconf"},
	},
	"E_NddTarget_VendorType": {
		1: {Name: "undefined"},
		2: {Name: "nokia-srl"},
		3: {Name: "nokia-sros"},
	},
}

var (
	// ySchema is a byte slice contain a gzip compressed representation of the
	// YANG schema from which the Go code was generated. When uncompressed the
	// contents of the byte slice is a JSON document containing an object, keyed
	// on the name of the generated struct, and containing the JSON marshalled
	// contents of a goyang yang.Entry struct, which defines the schema for the
	// fields within the struct.
	ySchema = []byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x9c, 0x5f, 0x73, 0xe3, 0x34,
		0x10, 0xc0, 0xdf, 0xfb, 0x29, 0x8c, 0x80, 0xe1, 0x5f, 0x4d, 0x93, 0x92, 0xb6, 0x77, 0x61, 0x18,
		0x28, 0xb4, 0x37, 0xcc, 0xdc, 0xf5, 0xb8, 0xe1, 0x6e, 0x78, 0xe0, 0x28, 0x45, 0xb5, 0x37, 0xa9,
		0xa6, 0x8e, 0xe4, 0x91, 0xe4, 0x5c, 0x02, 0x94, 0xcf, 0xce, 0x38, 0x4e, 0x1d, 0x3b, 0x89, 0xf5,
		0x27, 0x99, 0xa6, 0xee, 0xcc, 0x3e, 0xb5, 0xb1, 0x77, 0xa5, 0xd5, 0xea, 0xb7, 0x6b, 0x45, 0x2b,
		0xe7, 0x9f, 0xbd, 0x20, 0x08, 0x02, 0xf2, 0x9a, 0x8e, 0x80, 0xf4, 0x03, 0x12, 0xc3, 0x98, 0x45,
		0x40, 0xf6, 0x8b, 0xab, 0x2f, 0x19, 0x8f, 0x49, 0x3f, 0xe8, 0xce, 0x3f, 0xfe, 0x24, 0xf8, 0x80,
		0x0d, 0x49, 0x3f, 0xe8, 0xcc, 0x2f, 0x9c, 0x31, 0x49, 0xfa, 0x41, 0xd1, 0xc4, 0xec, 0x82, 0xa6,
		0x72, 0x08, 0x3a, 0x04, 0xae, 0xe5, 0xb4, 0x76, 0xa7, 0xd6, 0x49, 0x4d, 0x6a, 0xbf, 0x2e, 0x53,
		0xef, 0xb2, 0xbc, 0xbc, 0xdc, 0x75, 0x79, 0xe3, 0x8d, 0x84, 0x01, 0x9b, 0xac, 0xf4, 0x55, 0xeb,
		0x8f, 0xc7, 0x71, 0x58, 0xf4, 0xb9, 0xd4, 0xdb, 0x4c, 0xea, 0xad, 0xc8, 0x64, 0x04, 0x6b, 0x5b,
		0x28, 0x2c, 0x82, 0xe9, 0x07, 0x21, 0x73, 0xa3, 0x48, 0x5a, 0x74, 0xb6, 0xbf, 0x5e, 0xf0, 0x67,
		0xaa, 0x4e, 0xe5, 0x30, 0x1b, 0x01, 0xd7, 0xa4, 0x1f, 0x68, 0x99, 0x41, 0x83, 0x60, 0x45, 0xaa,
		0x6a, 0xdb, 0x8a, 0xf0, 0x5d, 0xed, 0xca, 0xdd, 0xd2, 0xc8, 0x97, 0x9d, 0x5f, 0xde, 0xa0, 0xf1,
		0x88, 0xf1, 0x50, 0x69, 0xaa, 0x0d, 0xa3, 0xba, 0xf7, 0x4d, 0x55, 0xb8, 0xc1, 0xdc, 0x33, 0x18,
		0xd0, 0x2c, 0xc9, 0xad, 0x7d, 0xbf, 0x56, 0x60, 0x26, 0x04, 0x9c, 0x5e, 0x27, 0x40, 0xd6, 0x0a,
		0x5c, 0x36, 0x34, 0x3c, 0x9f, 0xeb, 0x4e, 0xc3, 0xed, 0xa6, 0x39, 0x77, 0x99, 0x7b, 0x3f, 0x06,
		0x5c, 0x59, 0xf0, 0x66, 0xc2, 0x9b, 0x0d, 0x6f, 0x46, 0xd6, 0xb3, 0xd2, 0xc0, 0x4c, 0xd9, 0xfa,
		0xbb, 0x69, 0x0a, 0x6e, 0x7e, 0xb3, 0xf3, 0x51, 0x0b, 0xdb, 0x9e, 0x41, 0xe6, 0x9c, 0x67, 0xa3,
		0xbc, 0xd3, 0x06, 0x53, 0xf7, 0x1c, 0x8c, 0x27, 0xd1, 0x3d, 0x13, 0x16, 0xac, 0xe7, 0x72, 0x66,
		0xf0, 0xba, 0x08, 0xde, 0xae, 0xc1, 0x6b, 0x4a, 0x5a, 0x95, 0xe4, 0x15, 0x4b, 0x50, 0xca, 0xee,
		0x89, 0x05, 0xa0, 0x85, 0x82, 0x65, 0x58, 0xe6, 0x5c, 0xe3, 0x3c, 0xf5, 0x3e, 0x08, 0x6c, 0x86,
		0x82, 0x2f, 0x12, 0x1b, 0xa3, 0xb1, 0x31, 0x22, 0x1b, 0xa3, 0x62, 0x46, 0xc6, 0x82, 0x8e, 0x7b,
		0xee, 0x5a, 0xf1, 0xbb, 0xd2, 0x92, 0xf1, 0xa1, 0x8b, 0xcf, 0xef, 0x13, 0xc3, 0xb3, 0xbd, 0xcd,
		0xec, 0x37, 0xd8, 0x4e, 0x22, 0x09, 0x31, 0x70, 0xcd, 0x68, 0x12, 0xf2, 0xc2, 0x30, 0x47, 0xc2,
		0x97, 0x15, 0x91, 0x74, 0x24, 0xbd, 0xd5, 0xa4, 0x03, 0x8f, 0x44, 0x9c, 0xdb, 0xe1, 0x8c, 0x78,
		0xa9, 0x81, 0x6c, 0x23, 0xdb, 0xdb, 0x31, 0xe2, 0xba, 0x1c, 0x75, 0x5c, 0x96, 0x6e, 0x17, 0x09,
		0x8c, 0x2b, 0x88, 0x32, 0xe9, 0x91, 0xec, 0x4b, 0x0d, 0x8c, 0x04, 0x8c, 0x84, 0x06, 0xbf, 0x5f,
		0x0b, 0x91, 0x00, 0xe5, 0x3e, 0x81, 0xd0, 0x7d, 0x00, 0xb8, 0x53, 0x29, 0xb4, 0x88, 0x44, 0xe2,
		0x0e, 0x77, 0xa9, 0x61, 0x71, 0x89, 0xcb, 0x8e, 0x43, 0x29, 0x3c, 0xe4, 0x23, 0x66, 0x9e, 0xa3,
		0x4b, 0x8c, 0x25, 0x8c, 0xa5, 0xed, 0x90, 0x6c, 0xd5, 0x53, 0x25, 0x95, 0x62, 0x32, 0xf5, 0x8a,
		0xba, 0xc9, 0x14, 0x9f, 0x27, 0x18, 0x03, 0xed, 0xfe, 0xd6, 0xa0, 0x6e, 0x59, 0x1a, 0x8e, 0x41,
		0xb2, 0x81, 0x07, 0xdb, 0x55, 0x25, 0x24, 0x1c, 0x09, 0x6f, 0xf7, 0x8a, 0x49, 0x27, 0x2a, 0xdc,
		0x78, 0x1b, 0x68, 0x9d, 0x32, 0x22, 0x8f, 0xc8, 0x3f, 0x7e, 0x52, 0xf7, 0xaa, 0x00, 0x9c, 0x72,
		0x2e, 0x34, 0xd5, 0x4c, 0x70, 0x73, 0x21, 0x40, 0x45, 0x37, 0x30, 0xa2, 0x29, 0xd5, 0x37, 0xf9,
		0x68, 0x0e, 0x16, 0xae, 0x3e, 0xa8, 0x96, 0x8f, 0x0f, 0x8c, 0x85, 0x9e, 0xa2, 0x21, 0x2d, 0xb3,
		0x48, 0xcf, 0x63, 0x8d, 0xbc, 0x8e, 0xe3, 0x77, 0x33, 0xfd, 0xab, 0xe2, 0xcf, 0x79, 0xde, 0xca,
		0xd5, 0x3c, 0x02, 0xb6, 0x28, 0x4c, 0xc5, 0xa0, 0x22, 0xc9, 0x52, 0xe3, 0xb8, 0x2a, 0x55, 0xf6,
		0x85, 0x30, 0xd6, 0x46, 0x9f, 0x6c, 0x6d, 0xd4, 0x3e, 0x8d, 0xf5, 0xf8, 0x32, 0xc8, 0xbc, 0x02,
		0x3e, 0x9c, 0x91, 0x6e, 0xfe, 0xc2, 0xeb, 0x10, 0xff, 0x17, 0x8c, 0xbb, 0xa7, 0xcf, 0xdf, 0x68,
		0x92, 0x41, 0x73, 0x25, 0x74, 0x45, 0xfe, 0x85, 0xa4, 0x51, 0x3e, 0xdc, 0x33, 0x36, 0x64, 0x5a,
		0xd9, 0x9f, 0x18, 0x0b, 0x97, 0xc1, 0x90, 0x6a, 0x36, 0xce, 0xfb, 0x1a, 0xd0, 0x44, 0x81, 0x3d,
		0x5d, 0x3a, 0x24, 0xae, 0x0b, 0x3a, 0xf1, 0x1f, 0xea, 0xe1, 0xd1, 0x51, 0xfb, 0x06, 0xbb, 0x61,
		0xe6, 0x35, 0x6c, 0x6c, 0x90, 0x37, 0x54, 0x6b, 0x90, 0xdc, 0x8a, 0x14, 0x79, 0x7f, 0x1a, 0xfe,
		0x4e, 0xc3, 0xbf, 0x3b, 0xe1, 0xf3, 0xe0, 0xa3, 0x1f, 0x3e, 0xfe, 0xe4, 0xd3, 0x3f, 0xff, 0xc8,
		0x3a, 0x9d, 0xc3, 0xe3, 0xcf, 0xbf, 0xf8, 0xf7, 0xab, 0xef, 0xfe, 0xfa, 0xef, 0xeb, 0xfd, 0xcf,
		0x0e, 0xae, 0xfa, 0xdf, 0x7e, 0x1f, 0x5e, 0x7e, 0xd9, 0x1c, 0x60, 0x97, 0x5b, 0x24, 0x4e, 0xe3,
		0x22, 0x68, 0x91, 0xa2, 0x9a, 0x57, 0x3b, 0x98, 0x2a, 0x9f, 0x40, 0xaa, 0xb4, 0xac, 0x56, 0x31,
		0x47, 0x62, 0x8e, 0xc4, 0x1c, 0xd9, 0x98, 0x23, 0x1d, 0xcf, 0xf2, 0x19, 0x4f, 0xf1, 0xb9, 0x9e,
		0x79, 0x3a, 0xc4, 0x2c, 0xb9, 0xeb, 0x33, 0x4f, 0x37, 0x42, 0x69, 0xbf, 0xbd, 0x80, 0x52, 0x03,
		0x37, 0x00, 0x70, 0x03, 0xa0, 0xd5, 0xbb, 0xba, 0xb7, 0x45, 0xdb, 0x8e, 0x5c, 0xcf, 0xa4, 0x91,
		0x69, 0x64, 0xba, 0xd5, 0x4c, 0x8f, 0x68, 0x14, 0x7a, 0x9f, 0x53, 0xad, 0x2a, 0x21, 0xe1, 0x48,
		0x78, 0xab, 0x09, 0x57, 0x20, 0x67, 0x35, 0x86, 0x6c, 0x74, 0x0d, 0xd2, 0xa3, 0x1a, 0x57, 0x53,
		0x43, 0xca, 0x91, 0xf2, 0x76, 0x53, 0x9e, 0xa5, 0xa9, 0x90, 0x1a, 0xe2, 0xf0, 0xfe, 0x6c, 0xa1,
		0x47, 0x3e, 0x5f, 0xa7, 0x8c, 0xc4, 0x23, 0xf1, 0xbb, 0x22, 0xde, 0x62, 0xe1, 0x2b, 0xa6, 0xf4,
		0xa9, 0xd6, 0xd2, 0xcd, 0xca, 0x0b, 0xc6, 0xcf, 0x13, 0xc8, 0xfd, 0xe8, 0xb8, 0x87, 0x43, 0x2e,
		0xe8, 0xa4, 0xa2, 0xd1, 0x7d, 0xd6, 0xeb, 0x1d, 0x9f, 0xf4, 0x7a, 0x9d, 0x93, 0x6f, 0x4e, 0x3a,
		0xcf, 0x8f, 0x8e, 0xba, 0xc7, 0x5d, 0x87, 0x1d, 0x24, 0xf2, 0x8b, 0x8c, 0x41, 0x42, 0xfc, 0xe3,
		0x94, 0xf4, 0x03, 0x9e, 0x25, 0xc9, 0x43, 0xc4, 0xf8, 0x87, 0x70, 0x0c, 0x52, 0xd9, 0xca, 0x8d,
		0xf5, 0xb9, 0x5a, 0xe8, 0x60, 0x44, 0x63, 0x44, 0xb7, 0xfa, 0x19, 0x36, 0x06, 0x1e, 0x0b, 0x19,
		0x6a, 0x17, 0xf3, 0x4b, 0xd3, 0xab, 0x4a, 0x48, 0x38, 0x12, 0xbe, 0x35, 0x26, 0xc1, 0xce, 0x8f,
		0xc7, 0x3e, 0xe6, 0x99, 0x13, 0xeb, 0xdb, 0xd0, 0x2e, 0x47, 0x4e, 0xde, 0xce, 0x1a, 0xd9, 0xa2,
		0x28, 0xe0, 0x12, 0xf9, 0x1e, 0x53, 0xe9, 0xf6, 0x9a, 0x7f, 0xc6, 0x63, 0x18, 0x30, 0x0e, 0x31,
		0xbe, 0xe9, 0xff, 0x34, 0x8a, 0x0f, 0xee, 0x25, 0x5a, 0xb7, 0x68, 0x7f, 0x98, 0x37, 0xfd, 0x8d,
		0x3f, 0x74, 0xf1, 0x12, 0xa6, 0x0d, 0x25, 0x64, 0xf3, 0x2a, 0xd7, 0xbe, 0xaa, 0xdd, 0x68, 0x15,
		0x6b, 0x5e, 0xb5, 0x2e, 0x1b, 0x6f, 0x49, 0x3d, 0x8e, 0x29, 0x87, 0xac, 0x2d, 0x0a, 0x5a, 0x93,
		0x4c, 0x1d, 0xa2, 0x85, 0x97, 0x8b, 0xff, 0xe6, 0xa6, 0x36, 0x99, 0x48, 0x98, 0x7a, 0x41, 0x6f,
		0xe1, 0x57, 0x21, 0x56, 0x41, 0x5e, 0x36, 0x9b, 0x54, 0x6f, 0xd5, 0xec, 0x3a, 0x2b, 0x7e, 0x50,
		0xa6, 0xe8, 0x70, 0xef, 0xee, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
		0x7b, 0x44, 0x74, 0x84, 0x6f, 0x46, 0x00, 0x00,
	}
)

// ΛEnumTypes is a map, keyed by a YANG schema path, of the enumerated types that
// correspond with the leaf. The type is represented as a reflect.Type. The naming
// of the map ensures that there are no clashes with valid YANG identifiers.
var ΛEnumTypes = map[string][]reflect.Type{
	"/target-entry/admin-state": []reflect.Type{
		reflect.TypeOf((E_NddCommon_AdminState)(0)),
	},
	"/target-entry/config/encoding": []reflect.Type{
		reflect.TypeOf((E_NddTarget_Encoding)(0)),
	},
	"/target-entry/config/protocol": []reflect.Type{
		reflect.TypeOf((E_NddTarget_Protocol)(0)),
	},
	"/target-entry/state/vendor-type": []reflect.Type{
		reflect.TypeOf((E_NddTarget_VendorType)(0)),
	},
	"/target-entry/vendor-type": []reflect.Type{
		reflect.TypeOf((E_NddTarget_VendorType)(0)),
	},
}
