---
apiVersion: target.yndd.io/v1
kind: Target
metadata:
  name: leaf2
spec:
  properties:
    name: leaf2
    admin-state: enable
    vendor-type: nokia-sros
    config:
      protocol: gnmi
      address: 172.20.20.5:57400
      credential-name: srl-secrets
      encoding: JSON_IETF
      skip-verify: true