//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 NDD.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by ndd-gen. DO NOT EDIT.

package v1

import nddv1 "github.com/yndd/ndd-runtime/apis/common/v1"

// GetNetworkNodeReference of this TargetUsage.
func (p *TargetUsage) GetTargetReference() nddv1.Reference {
	return p.TargetReference
}

// GetResourceReference of this TargetUsage.
func (p *TargetUsage) GetResourceReference() nddv1.TypedReference {
	return p.ResourceReference
}

// SetTargetReference of this TargetUsage.
func (p *TargetUsage) SetTargetReference(r nddv1.Reference) {
	p.TargetReference = r
}

// SetResourceReference of this TargetUsage.
func (p *TargetUsage) SetResourceReference(r nddv1.TypedReference) {
	p.ResourceReference = r
}
